### ISSUE TITLE
MRS Manager访问方式

### ISSUE THREAD

**Issue by SmirkCao** [huaweicloudDocs/mrs#1]
适用于MRS 1.8.0及以后版本
https://<弹性公网IP>:9022/mrsmanager?locale=zh-cn

这个直接访问是不行的。

但是hwc提供的方式很方便，可以通过对应集群的**集群管理页面>点击查看**，hwc会导引添加访问IP，进入MRS Manager。

觉得这部分内容可以补充下

**Comment by hwgaoxiaofeng** [comment]
通过“集群管理页面>点击查看”方式访问MRS Manager及组件的开源界面已有对应资料，参见https://support.huaweicloud.com/usermanual-mrs/mrs_01_0646.html，此处的地址列表仅做参考，在列表上方已经经增加对应访问方式的链接
